name: Wake Backend & Run Cron

on:
  schedule:
    - cron: "*/5 * * * *"   # every 1 minutes
  workflow_dispatch:        # manual trigger (optional)

jobs:
  wake-and-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Wake backend
        run: |
          curl -s https://eventhubbackend-xi7u.onrender.com/api/cronjob/healthcheck
